### ISSUE TITLE
How to correctly uninstall the repo package ?

### ISSUE THREAD

**Issue by rpereira90** [GetPageSpeed/getpagespeed-extras-release#1]
sudo dnf install https://extras.getpagespeed.com/release-el8-latest.rpm
ok
sudo dnf remove getpagespeed-extras-release

Now everytime I run a yum or a dnf command I get this error:

Failed loading plugin "getpagespeed": No module named 'dnf.plugin.dynamic.getpagespeed'

**Comment by dvershinin** [comment]
It's a bug in the release package. Thanks for reporting.

You can:

    rm -rf /usr/lib/python3.6/site-packages/dnf-plugins/getpagespeed.py

**Comment by dvershinin** [comment]
Fixed in `getpagespeed-extras-release-10-12.noarch`

**Comment by rpereira90** [comment]
Thank you @dvershinin
